'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var FORM_VALIDATE = exports.FORM_VALIDATE = 'FORM_VALIDATE';
var FORM_SINGLE_VALIDATE = exports.FORM_SINGLE_VALIDATE = 'FORM_SINGLE_VALIDATE';
var FORM_INPUT_CHANGE = exports.FORM_INPUT_CHANGE = 'FORM_INPUT_CHANGE';
var FORM_RESET = exports.FORM_RESET = 'FORM_RESET';
var FORM_INITIAL_DATA = exports.FORM_INITIAL_DATA = 'FORM_INITIAL_DATA';
var FORM_DATA_REPLACE = exports.FORM_DATA_REPLACE = 'FORM_DATA_REPLACE';
var FORM_DATA_MERGE = exports.FORM_DATA_MERGE = 'FORM_DATA_MERGE';
var FORM_TRIGGER_VALIDATION = exports.FORM_TRIGGER_VALIDATION = 'FORM_TRIGGER_VALIDATION';

var HAS_VALUE_CLASS_NAME = exports.HAS_VALUE_CLASS_NAME = '_has-value';
var ERROR_INPUT_CLASS_NAME = exports.ERROR_INPUT_CLASS_NAME = '_is-error';
var ERROR_MSG_CLASS_NAME = exports.ERROR_MSG_CLASS_NAME = 'form-msg-error';
//# sourceMappingURL=formConstants.js.map